# Generated by Django 5.1.5 on 2025-07-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=256)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
